### ISSUE TITLE
Lots of PDF export problems

### ISSUE THREAD

**Issue by kpennell** [jsonresume/resume-cli#346]
Hi guys -
I really appreciate all the work you've done on the tool over the last couple years. I've used it pretty much for all my resumes for the last five years I'd say. 

Recently I'm having problems with the PDF exports. They seem to render quite differently than the HTML versions and I'm finding this across most of the themes. Either the HTML and CSS doesn't render properly so margins and padding is all messed up or there are some odd examples where different parts of the texts are cut off in the pdf version but not the HTML version. 

Any ideas for how to remedy this? Or where I should start troubleshooting?

**Comment by randytarampi** [comment]
Hey.

It might be a bit more helpful if you could provide a couple more details (or even examples) about the defects you're seeing, especially which particular problems you're seeing in particular themes.

From my experience, this is just because most themes just don't translate very well over to paper sizes. The `resume` CLI utility is probably fine as [my own theme](https://www.npmjs.com/package/jsonresume-theme-randytarampi) seems to render [as intended](https://github.com/randytarampi/me.resume/blob/master/a4.pdf).

That said, [I am using my own fork](https://github.com/randytarampi/resume-cli/tree/me-release), with the latest `puppeteer@2`, so your mileage may vary otherwise.

**Comment by thomasdavis** [comment]
PDF generation has been the bane of this project (and I'm sure many others) 

Other then following @randytarampi advice above (make your own theme that renders well as a pdf) 

I suggest playing with the advanced options of print to pdf in chrome. And/or trying themes such as `paper`
