### ISSUE TITLE
Export with local theme

### ISSUE THREAD

**Issue by jbttn** [jsonresume/resume-cli#51]
There is no way to get the export command to use a local theme, everything goes through the theme server.  This doesn't work for people who want to export with a theme they have created, but don't want to expose it to everyone else.  This also doesn't work for people who wish to export without being connected to the internet.

It would be nice if there was a flag which would force the export command to use a theme located locally on the users filesystem.

**Comment by chrisdotcode** [comment]
I'm on it.

Off the top of my head, I'm thinking of three possible ways to implement this:

1. Use a switch, `--local` or something, to specify that a local theme should be used instead.
2. Parse the variable given for `--theme`, and if it's an absolute uri, use that theme, instead of hitting the server (remember, bash expands your `~`s and `'./`s.
3. If the server doesn't have the theme, search locally for that theme instead.

Actually, maybe all of these can be used at once: you can either give an explicit `--local` flag, an absolute uri from root, or if the server fails to find your theme, it searches for a local one with the same name in some `$location`.

What does everybody else thing?
