### ISSUE TITLE
Anyway to parse a pdf or word doc into resume.json?

### ISSUE THREAD

**Issue by ralyodio** [jsonresume/resume-cli#712]
I’m looking for a way to parse resumes in pdf or word doc and output a json resume.

**Comment by thomasdavis** [comment]
I don't believe there have been any attempts that made it simple, you would likely be better just copying and pasting.

**Comment by SethFalco** [comment]
This is out of scope for resume-cli, but you can use an open-source resume parser, which should achieve what you want with decent results.

You'd need to adapt the output to fit the JSON Resume spec, but otherwise it handles most of the work for you.

I'd recommend one of these, I've used both of these to ensure my theme was machine parsable, and both pleasant to work with:

* [OmkarPathak/pyresparser](https://github.com/OmkarPathak/pyresparser)
* [kbrajwani/resume_parser](https://github.com/kbrajwani/resume_parser)
