### ISSUE TITLE
Client side HTML to PDF conversion

### ISSUE THREAD

**Issue by mchelen** [jsonresume/resume-cli#72]
Currently http://pdfcrowd.com/ is being used to generate PDF from HTML. Are there any other options that would work entirely client side? Depending on a 3rd party service means being reliant on their server status, pricing, and feature set. 

These are the export systems that have been tried so far:
- [`html-pdf`](https://www.npmjs.org/package/html-pdf) ([phantomjs](http://phantomjs.org/) wrapper) - Loses some formatting 
- [`wkhtmltopdf`](http://wkhtmltopdf.org/) - Loses some formatting

**Comment by howardroark** [comment]
I should think that PhantomJS would take care of this nicely.  I notice a lot of talk about print.css and I am slightly confused.

Would the goal not be to design responsive templates which can be sized to A4 paper dimensions from which a PDF would be generated as a snapshot?

**Comment by mchelen** [comment]
Feel free to test PhantomJS and see what the output quality is like. I'm not sure if anyone has tried that one specifically yet.

Regarding CSS print media, "responsive" often means including different CSS for various display formats. In this case, that might mean not underlining a link when printing, not including buttons, etc.

**Comment by thomasdavis** [comment]
Just adding this service to the discussion -> http://www.printfriendly.com/

**Comment by howardroark** [comment]
In my view PDFs are less about being printer friendly and more about preserving an aesthetic across platforms while being easily uploaded to online forms and attached to emails.  By the time someone prints your resume it is likely at the point they are meeting you in person.  (Most companies these days are getting pretty tight about paper usage.)

The real trick would be to ensure that all links and buttons remain clickable so that someone can spend time browsing your stuff.  The more time they spend thinking about you, the more likely you get an interview.

I know PhantomJS is working to make links usable in PDF output, but it is still in the pipe.  Either way I will report back if I have something to show :)

**Comment by TimDaub** [comment]
I think we should collect requirements a future to-PDF-converter should have.

- Must be an automated process
- Should be embeddable in resume-cli easily (light dependency byte-wise)
- Should not need an internet connection
- Must preserve features the html version of the resume has (hyperlinks, pictures, layout, formating, selectable text)
- Must be style-able externally of html version (with an print tag for example)

Do we have even more requirements?

**Comment by Simonn-** [comment]
Any progress on this?

**Comment by FranciscoG** [comment]
Not sure if this is still an issue since this is so old but I just installed the resume-cli and I noticed the PhantomJS dependency and that lead me to here.

I suggest switching from PhantomJS (which has completely stopped development) to Chrome-Headless and use their own node-library [Puppeteer](https://github.com/GoogleChrome/puppeteer) to control it.  I'm using it for screenshots and it works very well.  It has a built in PDF generator.   This is not "entirely client-side" but neither is using PhantomJS so thought it was worth mentioning

> Must be an automated process

it does.  It also installs its own Chromium.  But it does require Node version 7.10 or greater

> Should be embeddable in resume-cli easily (light dependency byte-wise)

Not light because of the Chromium dependency but I think it's worth the tradeoff: 
"Chromium (~71Mb Mac, ~90Mb Linux, ~110Mb Win) that is guaranteed to work with the API."

> Should not need an internet connection

The [API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetcontenthtml) allows you to inject html directly into it so it doesn't need an internet connection to use

> Must preserve features the html version of the resume has (hyperlinks, pictures, layout, formating, selectable text)

> Must be style-able externally of html version (with an print tag for example)

It's basically Chrome so it HTML and CSS works as you would expect

Idk, might be worth checking out  ¯\_(ツ)_/¯

**Comment by PeterDaveHello** [comment]
This may also help:
https://github.com/alvarcarto/url-to-pdf-api

**Comment by FranciscoG** [comment]
@PeterDaveHello that library [uses the Puppeteer package](https://github.com/alvarcarto/url-to-pdf-api/blob/master/package.json#L32) I mentioned above and it also installs Express.   I think it might be overkill.  It's trivial to write a one module script that loads Puppeteer and makes a PDF.  But i'm not totally discounting it, it might also be worth looking into

**Comment by narkhedetushar** [comment]
can we try something like this https://github.com/fraserxu/electron-pdf

**Comment by thomasdavis** [comment]
electron-pdf looks worth investigating. 

https://github.com/jsonresume/resume-cli/issues/385
https://github.com/jsonresume/resume-cli/issues/389
