### ISSUE TITLE
Accept "Present" as a valid "endDate" value

### ISSUE THREAD

**Issue by seppzer0** [jsonresume/resume-cli#762]
Let's say, I want to specify that I am still studiying in my college and/or still working at some company.
In that case, it would be appropriate to set a "Present" value for the `endDate` parameter in resume.json .

I found that "Present" value actually works properly when specified in `work` block of the resume.json -- and it does render sucessfully when running `resume serve`.
However, when trying the same for `education` -- the `endDate` renders as `Invalid Date` (e.g. below).
![image](https://user-images.githubusercontent.com/36642137/227358163-b64b69f0-fbf1-408d-96a3-37c776ccc926.png)

So, it would be great if a `Present` is accepted as a valid value throughout all blocks of resume.json description!

**Comment by seppzer0** [comment]
Closing the issue as the project seems to be, unfortunately, dead.

**Comment by SethFalco** [comment]
Sorry that you didn't get a timely response for this.

This is actually dependent on the theme you're using rather than the spec. The spec already makes the end date optional, which is meant to represent that it's an ongoing tenure.

The theme should be checking if the end date is defined. If you remember, would you be able to share which theme you were using?
